services:
  redis:
    image: redis:latest
    container_name: tegola-redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: mysecurepassword
    command: redis-server --requirepass mysecurepassword --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  tegola-mvt-postgis-provider:
    image: gospatial/tegola:v0.16.0
    container_name: tegola-mvt-postgis-provider
    restart: "unless-stopped"
    ports:
      - 8080:8080
    volumes:
      - ./config:/data
    command: >
      serve --config /data/config-mvt-postgis.toml
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: urbandata
      DB_USER: postgres
      DB_PASSWORD: postgres
      TEGOLA_POSTGIS_SSL: disable
      TEGOLA_REDIS_SSL: false
      REDIS_HOST: redis:6379
      REDIS_PASSWORD: mysecurepassword
      TEGOLA_SQL_DEBUG: LAYER_SQL
