services:
  redis:
    image: redis:latest
    container_name: tegola-redis
    ports:
      - 6379:6379

  tegola-mvt-postgis-provider:
    image: gospatial/tegola:v0.16.0
    container_name: tegola-mvt-postgis-provider
    restart: "unless-stopped"
    ports:
      - 8080:8080
    volumes:
      - ./config:/data
    command: >
      serve --config /data/config-mvt-postgis.toml
    environment:
      DB_HOST: db-postgresql-fra1-81904-do-user-15998940-0.c.db.ondigitalocean.com
      DB_PORT: 25060
      DB_NAME: defaultdb
      DB_USER: doadmin
      DB_PASSWORD: AVNS_vzGFs6VuYr5BHKpOB2w
      TEGOLA_POSTGIS_SSL: require
      TEGOLA_REDIS_SSL: false
      REDIS_HOST: redis:6379
      REDIS_PASSWORD: ""
      TEGOLA_SQL_DEBUG: LAYER_SQL