[webserver]
port = ":8080"

[webserver.headers]
Cache-Control = "s-maxage=3600"

[cache]
type = "redis"
address = "${REDIS_HOST}"
password = "${REDIS_PASSWORD}"
ttl = 10
max_zoom = 18
ssl = "${TEGOLA_REDIS_SSL}"
db = 1

[[providers]]
name = "germany"
type = "mvt_postgis"
uri = "postgresql://doadmin:AVNS_vzGFs6VuYr5BHKpOB2w@db-postgresql-fra1-81904-do-user-15998940-0.c.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
srid = 4326


  [[providers.layers]]
  name = "power_line"
  geometry_fieldname = "wkb_geometry"
  geometry_type = "linestring"  # "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, ogc_fid , voltage, operator FROM power_line WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "other_power_line"
  geometry_fieldname = "wkb_geometry"
  geometry_type = "linestring"  # "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, ogc_fid , voltage, operator FROM other_power_lines WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "substation_area"
  geometry_fieldname = "wkb_geometry"
  geometry_type = "polygon"  # or "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry,operator,mittelspannung_operator, ogc_fid FROM substations WHERE wkb_geometry && !BBOX!"


  [[providers.layers]]
  name = "substation_point"
  geometry_fieldname = "node"
  geometry_type = "point"  # or "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = """
    SELECT 
      ST_AsMVTGeom(node, !BBOX!) AS node, 
      ogc_fid, 
      s_id, 
	  frequency, 
      name, 
      operator, 
      substation, 
      voltage, 
      operators, 
      color, 
      juni_nam, 
      mai_nam, 
      aktuell_nam, 
      mittelspannung_operator 
    FROM substations 
    WHERE node && !BBOX! 
    AND (
      CASE 
        WHEN !ZOOM! < 9 THEN area > 100000
        WHEN !ZOOM! < 6 THEN area > 50000  
        ELSE area > 0 
      END
    )
  """

  [[providers.layers]]
  name = "withoutzoom_substations"
  geometry_fieldname = "node"
  geometry_type = "point"  # or "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = """
    SELECT 
      ST_AsMVTGeom(node, !BBOX!) AS node, 
      ogc_fid, 
      s_id, 
	  frequency, 
      name, 
      operator, 
      substation, 
      voltage, 
      operators, 
      color, 
      juni_nam, 
      mai_nam, 
      aktuell_nam, 
      mittelspannung_operator 
    FROM substations 
    WHERE node && !BBOX! 
  """

  [[providers.layers]]
  name = "transformer"
  geometry_fieldname = "wkb_geometry"
  geometry_type = "point"  # or "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, ogc_fid,id,operator FROM transformers WHERE wkb_geometry && !BBOX!"


  [[providers.layers]]
  name = "tower"
  geometry_fieldname = "wkb_geometry"
  geometry_type = "point"  # or "polygon" or "linestring" depending on your data
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, ogc_fid, id FROM towers WHERE wkb_geometry && !BBOX!"

[[maps]]
name = "power"
center = [10.0, 51.0, 6.0] # Center of the map on Germany

  [[maps.layers]]
  provider_layer = "germany.power_line"
  min_zoom = 3
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "germany.other_power_line"
  min_zoom = 3
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "germany.substation_area"
  min_zoom = 13
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "germany.substation_point"
  min_zoom = 3
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "germany.transformer"
  min_zoom = 13
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "germany.tower"
  min_zoom = 13
  max_zoom = 20
  
   [[maps.layers]]
  provider_layer = "germany.withoutzoom_substations"
  min_zoom = 3
  max_zom = 20
  