[webserver]
port = ":8080"

[webserver.headers]
Cache-Control = "s-maxage=3600"

[cache]
type = "redis"
address = "${REDIS_HOST}"
password = "${REDIS_PASSWORD}"
ttl = 100 
max_zoom = 18
ssl = "${TEGOLA_REDIS_SSL}"
db = 1


[[providers]]
name = "germany"
type = "mvt_postgis"
uri = "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${TEGOLA_POSTGIS_SSL}" 
srid = 4326 

  [[providers.layers]]
  name = "vehicle_points"
  geometry_fieldname = "wkb_geometry"
  geometry_type="point"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry, polygon_name,created_at_date,vehicle_id,speed_kmph,vehicle_battery_charge, ogc_fid FROM vehicle_points WHERE wkb_geometry && !BBOX!"
  
  [[providers.layers]]
  name = "vehicle_routes"
  geometry_fieldname = "wkb_geometry"
  geometry_type="linestring"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsMVTGeom(wkb_geometry, !BBOX!) AS wkb_geometry,created_at_date,vehicle_id,speed_kmph,vehicle_battery_charge, ogc_fid FROM vehicle_routes WHERE wkb_geometry && !BBOX!"


[[maps]]
name = "urbandata"
center = [7.0982, 50.7374, 11.0] # set the center of the map so the user is auto navigated to Bonn

  [[maps.layers]]
  provider_layer = "germany.vehicle_points"
  min_zoom = 10
  max_zoom = 20
  
  [[maps.layers]]
  provider_layer = "germany.vehicle_routes"
  min_zoom = 10
  max_zoom = 20
